# 自动编译代码
name: Build Artifact

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Build With Docker
        run: docker run -t --rm -v $PWD:/project registry.cn-shenzhen.aliyuncs.com/liux-pro/wch-build
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ch582-ninja.hex
          path: ./build/ch582-ninja.hex
